"""add agent operations

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-10 23:15:24.501324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_ops_audit_heads',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('last_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('mobile_callback_nonces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=80), nullable=False),
    sa.Column('nonce', sa.String(length=80), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', 'nonce', name='uq_mobile_callback_nonce')
    )
    with op.batch_alter_table('mobile_callback_nonces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mobile_callback_nonces_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mobile_callback_nonces_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mobile_callback_nonces_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('agent_ops_contact_permissions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('destination_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('asserted_basis', sa.String(length=60), nullable=False),
    sa.Column('source_reference', sa.String(length=500), nullable=False),
    sa.Column('evidence_digest', sa.String(length=64), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_ops_contact_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_ops_contact_permissions_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_contact_permissions_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_contact_permissions_destination_fingerprint'), ['destination_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_contact_permissions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_contact_permissions_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_contact_permissions_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_contact_permissions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('agent_ops_contact_suppressions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('destination_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'channel', 'destination_fingerprint', name='uq_agent_ops_contact_suppression')
    )
    with op.batch_alter_table('agent_ops_contact_suppressions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_ops_contact_suppressions_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_contact_suppressions_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_contact_suppressions_destination_fingerprint'), ['destination_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_contact_suppressions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('agent_ops_tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=80), nullable=False),
    sa.Column('workflow', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('work_order_json', sa.Text(), nullable=True),
    sa.Column('compliance_checked', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=32), nullable=True),
    sa.Column('audit_hash', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_ops_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_ops_tasks_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_tasks_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_tasks_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_tasks_workflow'), ['workflow'], unique=False)

    op.create_table('mobile_agents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=80), nullable=False),
    sa.Column('webhook_url', sa.String(length=2048), nullable=False),
    sa.Column('secret_ciphertext', sa.Text(), nullable=False),
    sa.Column('platform_specialty', sa.String(length=40), nullable=False),
    sa.Column('capabilities_json', sa.Text(), nullable=False),
    sa.Column('adapter_version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_ping', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', name='uq_mobile_agent_tenant_label')
    )
    with op.batch_alter_table('mobile_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mobile_agents_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mobile_agents_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_mobile_agents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('agent_ops_audit_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=True),
    sa.Column('agent_id', sa.String(length=80), nullable=False),
    sa.Column('workflow', sa.String(length=40), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('detail_digest', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['agent_ops_tasks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_hash'),
    sa.UniqueConstraint('tenant_id', 'sequence', name='uq_agent_ops_audit_tenant_sequence')
    )
    with op.batch_alter_table('agent_ops_audit_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_ops_audit_entries_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_audit_entries_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_audit_entries_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_ops_audit_entries_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_ops_audit_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_ops_audit_entries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_audit_entries_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_audit_entries_event'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_audit_entries_agent_id'))

    op.drop_table('agent_ops_audit_entries')
    with op.batch_alter_table('mobile_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mobile_agents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mobile_agents_created_by'))
        batch_op.drop_index(batch_op.f('ix_mobile_agents_agent_id'))

    op.drop_table('mobile_agents')
    with op.batch_alter_table('agent_ops_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_ops_tasks_workflow'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_tasks_agent_id'))

    op.drop_table('agent_ops_tasks')
    with op.batch_alter_table('agent_ops_contact_suppressions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_ops_contact_suppressions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_contact_suppressions_destination_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_contact_suppressions_created_by'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_contact_suppressions_channel'))

    op.drop_table('agent_ops_contact_suppressions')
    with op.batch_alter_table('agent_ops_contact_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_ops_contact_permissions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_contact_permissions_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_contact_permissions_purpose'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_contact_permissions_expires_at'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_contact_permissions_destination_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_contact_permissions_created_by'))
        batch_op.drop_index(batch_op.f('ix_agent_ops_contact_permissions_channel'))

    op.drop_table('agent_ops_contact_permissions')
    with op.batch_alter_table('mobile_callback_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mobile_callback_nonces_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mobile_callback_nonces_expires_at'))
        batch_op.drop_index(batch_op.f('ix_mobile_callback_nonces_agent_id'))

    op.drop_table('mobile_callback_nonces')
    op.drop_table('agent_ops_audit_heads')
    # ### end Alembic commands ###
